### ISSUE TITLE
bugfix fav_cnt after API cache revalidation 

### ISSUE THREAD

**Issue by VortexExpansion** [diverta/front_next_media#10]
https://github.com/diverta/Kuroco-opendev/issues/5833#issue-2106779520
@yabe-diverta

**Comment by VortexExpansion** [comment]
@HisashiHasebe san, any update on how to proceed with this implementation ?

**Comment by HisashiHasebe** [comment]
@VortexExpansion 
No I haven't, still waiting update...

**Comment by HisashiHasebe** [comment]
@VortexExpansion 
Temporarily disabled `/rcms-api/1/content/details /{topics_id}` cache.
Looks ok. I will update API after implement  purge cache function.
https://diverta.gyazo.com/b1d82c6e11d423aa37b00b2f5fa88de9

**Comment by VortexExpansion** [comment]
@HisashiHasebe san 

I confirmed. The favourite feature seems to work perfectly now. ✨ 
https://diverta.gyazo.com/4afd41a8bbec8bc5c48e05295b71cdde

I think you can close this issue for now. The purpose for this repository seems to have been served.
