### ISSUE TITLE
Styling minor fixes

### ISSUE THREAD

**Issue by VortexExpansion** [diverta/front_next_media#14]
@KuriharaMina san, can you have a look at these please ? 

- [x] Console warnings for image https://diverta.gyazo.com/edf1508fc96dd9db5fe303a48c7d13ad
- [x] AlertError style in `member/edit` screen https://diverta.gyazo.com/770b2a6578dabd7b83ef6586d9e7c3f1
- [x] AlertError style in `login` screen https://diverta.gyazo.com/a7cb725006f16c9849d4b0427b33ab70

@HisashiHasebe

**Comment by KuriharaMina** [comment]
@VortexExpansion @HisashiHasebe 
I have made the corrections, so please review. Thank you.

・Console warnings for image
https://github.com/diverta/front_next_media/commit/a7030d4eabfc7b7b471f528e180eb343f99592f1

・AlertError style 
https://github.com/diverta/front_next_media/commit/b8f55fa7ce6415b060057f44b91394d7c331a07b

**Comment by VortexExpansion** [comment]
@KuriharaMina san

AlertError style seems perfect. Thank you ✨ 
The previous warnings seems to have been resolved too, but I can see a new warning on my local now for `flex`
https://diverta.gyazo.com/ec4dbcf9960bb58b83ecffb388925c6d

Edit : Found another one https://diverta.gyazo.com/90307c8aea5dc8f2c665b4a9e70625ec


Can you check please ?

**Comment by VortexExpansion** [comment]
@yabe-diverta san can you please take a look

**Comment by yabe-diverta** [comment]
No errors found now in [the latest PR](https://github.com/diverta/front_next_media/pull/11)

### evidences

[browser](https://diverta.gyazo.com/faabfc01f1a559cbeb75e1e40bb33ecc)

<details>
<summary>both build & dev do not emit warnings/errors</summary>

```sh
~/w/front_next_media ❯❯❯ npm run build

> next-media@0.1.0 build
> next build

   ▲ Next.js 14.1.4
   - Environments: .env.local, .env

   Creating an optimized production build ...
 ✓ Generating static pages (51/51) 
 ✓ Collecting build traces    
 ✓ Finalizing page optimization    

Route (app)                              Size     First Load JS
┌ ○ /                                    186 B          96.5 kB
├ ○ /_not-found                          0 B                0 B
├ ○ /article                             2.42 kB        98.7 kB
├ ● /article/[id]                        1.87 kB        98.2 kB
├   ├ /article/39
├   ├ /article/22
├   ├ /article/16
├   └ [+31 more paths]
├ ○ /contact                             3.02 kB        94.3 kB
├ ● /feature/[id]                        903 B          97.2 kB
├   ├ /feature/20
├   └ /feature/17
├ ○ /login                               2.17 kB        93.5 kB
├ ○ /member/delete                       2.55 kB        93.8 kB
├ ○ /member/edit                         2.93 kB        94.2 kB
├ ● /member/limited/[id]                 2.16 kB        93.5 kB
├   └ /member/limited/[id]
├ ○ /member/mypage                       2.91 kB        99.2 kB
├ ○ /privacy                             175 B          91.5 kB
├ ○ /register                            2.47 kB        93.8 kB
└ ○ /reminder                            1.66 kB          93 kB
+ First Load JS shared by all            91.3 kB
  ├ chunks/69-c9cacc90c736f315.js        29.2 kB
  ├ chunks/fd9d1056-d56d421cdc185422.js  53.4 kB
  └ other shared chunks (total)          8.74 kB


○  (Static)  prerendered as static content
●  (SSG)     prerendered as static HTML (uses getStaticProps)

~/w/front_next_media ❯❯❯ npm run dev

> next-media@0.1.0 dev
> next dev

   ▲ Next.js 14.1.4
   - Local:        http://localhost:3000
   - Environments: .env.local, .env

 ✓ Ready in 1909ms
```

</details>
