### ISSUE TITLE
Header display when searching for tags

### ISSUE THREAD

**Issue by HisashiHasebe** [diverta/front_next_media#22]
In the header during tag searches, the categories of content are displayed randomly.

https://diverta.gyazo.com/27108c3bd6c8cb1d23d9d849ebc35e47

**Comment by VortexExpansion** [comment]
@HisashiHasebe san
I think the categories are not random. They are the corresponding content categories of search results.

I also believe this change is intended as this behaviour was specifically changed in #11 by @yabe-diverta san uniformly across all SearchQueryParams like `search` `tag area` and `tag keyword`. 

Initial behaviour : https://diverta.gyazo.com/2d8713135c9d3a0959762c864d54f531
New behaviour : https://diverta.gyazo.com/fa100fe6cdf5dbbcb25a0bcba2f28e42

**Comment by HisashiHasebe** [comment]
@VortexExpansion 
Umm, but The content displayed feels strange.
Let's ask to designer.

@mimori @KuriharaMina 
メディアサンプルサイトがビルドされました。
https://dev-next-media.g.kuroco-front.app/article/
next/media

記事一覧はクエリパラメータによる絞りこみによって、複数パターンが1つのページで表示されます。
記事一覧及び検索結果のページ `/article/` に表示される文言がどんなものが良いかご確認いただけますでしょうか。

主に三か所(パンくず、ヘッダー、h2)
https://diverta.gyazo.com/ad9c3b409daff23265a6375255cc17e4

私は絞り込んでいるカテゴリ名、タグ名、キーワードなどが表示される想定でした。。

ページ一覧表示：https://dev-next-media.g.kuroco-front.app/article/
カテゴリで絞込み：https://dev-next-media.g.kuroco-front.app/article/?topic=food
タグ検索時(タグカテゴリ=エリア)：https://dev-next-media.g.kuroco-front.app/article/?tag_category_id=5&tag_id=26
タグ検索時(タグカテゴリ=キーワード)：https://dev-next-media.g.kuroco-front.app/article/?tag_category_id=6&tag_id=27
キーワード検索時：https://dev-next-media.g.kuroco-front.app/article/?search=%E7%A9%B4%E5%A0%B4

**Comment by takel-shiba** [comment]
@KuriharaMina 
View ALLはTOPだけ出す

タグで検索したとき
一覧の上のサブタイトルに「#ホテルの検索結果」
→上のメインビジュアルの文字は固定（タグ検索？）

キーワードも同じ感じ

**Comment by KuriharaMina** [comment]
@HisashiHasebe @takel-shiba @VortexExpansion 
ビルドエラーでフロントに反映されないようなのでキャプチャにて説明させていただきます。
各HTMLはマージ済みです。
ご確認お願いいたします。

**■記事一覧（TOPからView ALLで遷移してきた時）**
・モックファイル
https://github.com/diverta/front_next_media/blob/main/public/mock/article/index_all.html

・フロント
https://diverta.gyazo.com/5accd3966c614547fb00853577764809

-----------------------------------------------------

**■グロナビからのカテゴリ絞り込み時**
・モックファイル
https://github.com/diverta/front_next_media/blob/main/public/mock/article/index.html

・フロント
https://diverta.gyazo.com/f3cc181bcad1873db0972e3e64cdfffe

-----------------------------------------------------

**■検索時**
・モックファイル
https://github.com/diverta/front_next_media/blob/main/public/mock/article/index_search.html

・フロント
https://diverta.gyazo.com/d12051ea9ecbd5f5669183a61b480bfe
※キーワード検索の時は、＃ なしでお願いします。

**Comment by HisashiHasebe** [comment]
@KuriharaMina 
Thank you for update!

@VortexExpansion 
Can you update it? https://github.com/diverta/front_next_media/issues/22#issuecomment-2074150103

**Comment by VortexExpansion** [comment]
@HisashiHasebe san 
Sure I'll work on it. 

@KuriharaMina san 
Could you please also attach the mock files and front for 

> When searching for tags (tag category = area): https://dev-next-media.g.kuroco-front.app/article/?tag_category_id=5&tag_id=26
> When searching for tags (tag category = keyword): [https: //dev-next-media.g.kuroco-front.app/article/?tag_category_id=6&tag_id=27When](https://dev-next-media.g.kuroco-front.app/article/?tag_category_id=6&tag_id=27)

**Comment by KuriharaMina** [comment]
@VortexExpansion 
Here is the mock for when searching by tags.
https://diverta.gyazo.com/e52d55ba265a14b51eff0d38ff1dd5b4


```
■検索時
・モックファイル
https://github.com/diverta/front_next_media/blob/main/public/mock/article/index_search.html

・フロント
https://diverta.gyazo.com/d12051ea9ecbd5f5669183a61b480bfe
```

**Comment by VortexExpansion** [comment]
@KuriharaMina san 

Sorry again. But can you send me mocks of specific examples for the following cases : 

- Case 1 : When the user types "hello" in the searchbar 
- Case 2 : When the user clicks on the tag `[東京]` in `エリアから探す`
- Case 3 : When the user clicks on the tag `[リラックス]` in `キーワードから探す`

**Comment by KuriharaMina** [comment]
@VortexExpansion 
Here is the file for the mock page.
Thank you for your confirmation.

- Case 1 : When the user types "hello" in the searchbar
https://github.com/diverta/front_next_media/blob/main/public/mock/article/free_keyword_search.html
キャプチャ：https://diverta.gyazo.com/f4ba75eeee127d22c30498a365be6eb2

- Case 2 : When the user clicks on the tag [東京] in エリアから探す
https://github.com/diverta/front_next_media/blob/main/public/mock/article/tag_area_search.html
キャプチャ：https://diverta.gyazo.com/6ce6f1f70adcc6da9e682f060d4bf8cd

- Case 3 : When the user clicks on the tag [リラックス] in キーワードから探す
https://github.com/diverta/front_next_media/blob/main/public/mock/article/tag_keyword_search.html
キャプチャ：https://diverta.gyazo.com/7d267c6f98a5dbd36a7a9aa988c42256

**Comment by VortexExpansion** [comment]
@KuriharaMina san 
Thank you so much for the confirmation. Clear now 🙇
