### ISSUE TITLE
feature list in sitemap.xml

### ISSUE THREAD

**Issue by VortexExpansion** [diverta/front_next_media#41]
@HisashiHasebe san 

Sitemap.xml has the wrong implementation for feature list currently. I will fix that. 
https://diverta.gyazo.com/d11d4da8cafafc621e1fa9fbb99c9b60

At the same time, there is no API for fetching information of all the featured stories. The only API is `/rcms-api/1/pickup/list` which has the condition of `cnt=2` for display. 

Suggestion : add a new API `/rcms-api/1/pickup/all` which recursively fetches all featured stories with pagination and perPage limit of `200` similar to the new behaviour of `/rcms-api/1/content/all` #40

**Comment by HisashiHasebe** [comment]
@VortexExpansion 
Currently, there is no pathway to access past featured articles. First, we need to fix the bug in sitemap.xml, and then we can discuss how to handle past featured articles separately.

**Comment by VortexExpansion** [comment]
@HisashiHasebe san

For fixing the bug, I need to replace the API for feature list. 
But like I mentioned, there is no API that contains all the articles of the feature list. 

I can use `/rcms-api/1/pickup/list` which would only return 2 articles. 

So what API do I use for this ?

**Comment by HisashiHasebe** [comment]
@VortexExpansion 
Does the sitemap need to include all articles, including past articles?

**Comment by HisashiHasebe** [comment]
@VortexExpansion 
I made `/rcms-api/1/pickup/all` (cnt=200), can you fix the bug using this API?
